backend = "fastresize"
color_space = "lab"
palette = "ansidark"
saturation = 45

[templates]
json = { template = "colors.json", target = "~/.cache/wallpapers/colors.json" }
waybar = { template = "waybar.css", target = "~/.config/waybar/colors.css" }
